import PrimeVue from "primevue/config";
import Menubar from "primevue/menubar";
import Menu from "primevue/menu";
import { useToast } from "primevue/usetoast";
import Card from "primevue/card";
import Panel from "primevue/panel";
import Divider from "primevue/divider";
import InputText from "primevue/inputtext";
import Editor from "primevue/editor";
import Textarea from "primevue/textarea";
import Button from "primevue/button";
import Accordion from "primevue/accordion";
import AccordionTab from "primevue/accordiontab";
import Carousel from "primevue/carousel";
import Timeline from "primevue/timeline";
import FileUpload from "primevue/fileupload";
import MultiSelect from "primevue/multiselect";
import TreeSelect from "primevue/treeselect";
import Password from "primevue/password";
import ConfirmDialog from "primevue/confirmdialog";
import DynamicDialog from "primevue/dynamicdialog";
import Dialog from "primevue/dialog";
import Sidebar from "primevue/sidebar";
import ScrollTop from "primevue/scrolltop";
import ScrollPanel from 'primevue/scrollpanel';
import Splitter from 'primevue/splitter';
import SplitterPanel from 'primevue/splitterpanel';
import { useDialog } from 'primevue/usedialog';
import OverlayPanel from 'primevue/overlaypanel';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(PrimeVue, { ripple: true });
  nuxtApp.vueApp.component("Menubar", Menubar);
  nuxtApp.vueApp.component("Menu", Menu);
  nuxtApp.vueApp.component("useToast", useToast);
  nuxtApp.vueApp.component("Card", Card);
  nuxtApp.vueApp.component("Panel", Panel);
  nuxtApp.vueApp.component("Divider", Divider);
  nuxtApp.vueApp.component("InputText", InputText);
  nuxtApp.vueApp.component("Editor", Editor);
  nuxtApp.vueApp.component("Textarea", Textarea);
  nuxtApp.vueApp.component("Button", Button);
  nuxtApp.vueApp.component("Accordion", Accordion);
  nuxtApp.vueApp.component("AccordionTab", AccordionTab);
  nuxtApp.vueApp.component("Carousel", Carousel);
  nuxtApp.vueApp.component("Timeline", Timeline);
  nuxtApp.vueApp.component("FileUpload", FileUpload);
  nuxtApp.vueApp.component("MultiSelect", MultiSelect);
  nuxtApp.vueApp.component("TreeSelect", TreeSelect);
  nuxtApp.vueApp.component("Password", Password);
  nuxtApp.vueApp.component("ConfirmDialog", ConfirmDialog);
  nuxtApp.vueApp.component("DynamicDialog", DynamicDialog);
  nuxtApp.vueApp.component("Dialog", Dialog);
  nuxtApp.vueApp.component("Sidebar", Sidebar);
  nuxtApp.vueApp.component("Splitter", Splitter);
  nuxtApp.vueApp.component("SplitterPanel", SplitterPanel);
  nuxtApp.vueApp.component("ScrollTop", ScrollTop);
  nuxtApp.vueApp.component("ScrollPanel", ScrollPanel);
  nuxtApp.vueApp.component("useDialog", useDialog);
  nuxtApp.vueApp.component("DataTable", DataTable);
  nuxtApp.vueApp.component("Column", Column);
  nuxtApp.vueApp.component("OverlayPanel", OverlayPanel);
  //other components that you need
});
